### ISSUE TITLE
question about model

### ISSUE THREAD

**Issue by nimuyc** [KuilongCui/MDPR#1]
Dear Author, deeply inspired by your paper, I would like to ask in which section the code about the network architecture part is located, I didn't find it when I was looking at your code. Looking forward to your answer.

**Comment by KuilongCui** [comment]
fastreid/modeling/meta_arch/mdpr.py

**Comment by nimuyc** [comment]
> fastreid/modeling/meta_arch/mdpr.py

thank you very much. I have found it.
