### ISSUE TITLE
Inference on own data

### ISSUE THREAD

**Issue by HeChengHui** [KuilongCui/MDPR#2]
@KuilongCui 
Thank you for your work.

Wonder if you are able to provide pretrained models to test it out?

**Comment by KuilongCui** [comment]
Please refer to [GETTING_STARTED.md](https://github.com/KuilongCui/MDPR/blob/master/GETTING_STARTED.md)

**Comment by HeChengHui** [comment]
@KuilongCui 
My bad i totally missed it.

If i want to test it on my own video frames, do i still look into tools/train_net.py? Or demo/demo.py?

**Comment by KuilongCui** [comment]
Here's a rough breakdown of the steps:
1. Download the pre-trained weights DukeMTMC-reID.pth and place it in the weights/ directory.
2. Put your dataset into the datasets/ directory.
3. Next, create a new class in fastreid/data/datasets to specify how to read your dataset.
4. Finally, adjust configs/MDPR/DukeMTMC.yml by changing the dataset setting to match your dataset.

**Comment by HeChengHui** [comment]
I dont have a dataset like DukeMTMC. I would like to use this to identify people in my database while running my video processing workflow.
Perhaps i should use FeatureExtractionDemo?

**Comment by KuilongCui** [comment]
I think perhaps you could refer to the Introduction section of this [paper](https://arxiv.org/pdf/2001.04193.pdf) on how to build a person re-identification system. I'm sorry, I also lack practical experience in relevant projects. In the issue section, I mainly address how to reproduce MDPR.

**Comment by KuilongCui** [comment]
If you don't have other questions, I will close this issue. @HeChengHui

**Comment by HeChengHui** [comment]
@KuilongCui 

Thank you for the paper recommendation. Seems like i am trying to do Open-World Re-ID. I would like to get the features extracted in your work to do cosine similarity/euclidean distance comparison Re-ID the person in my video. 

Hence, since i only want to extract the features, is it correct to look into [this](https://github.com/KuilongCui/MDPR/blob/89d973701fe2c51e55090b52e1537fc278b8c3a1/demo/demo.py#L86)?

**Comment by KuilongCui** [comment]
Yes. @HeChengHui 

You can try using the following command: 
`CUDA_VISIBLE_DEVICES=1 python demo/demo.py --config-file configs/MDPR/DukeMTMC.yml --parallel --input ./test_input/*.jpg --output ./test_output --opts MODEL.WEIGHTS weights/DukeMTMC-reID.pth`

Additionally, you may need to refer to [train_net.py](https://github.com/KuilongCui/MDPR/blob/89d973701fe2c51e55090b52e1537fc278b8c3a1/tools/train_net.py#L11 ) to add **add_mdpr_cfg(cfg)** in the setup_cfg function of demo.py.

**Comment by HeChengHui** [comment]
thanks. i will try it out.
